language:generic
sudo: required
services:
  - docker

before_install:
  - docker build -t platof/docker-react -f Dockerfile.dev .

script:
  - docker run platof/docker-react npm run test -- --coverage
