version: '3.7'

services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - '/app/node_modules'
      - '.:/app'
    environment:
      - NODE_ENV=development

  tests:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - '/app/node_modules'
      - '.:/app'
    command: ["npm", "run", "test"]
